-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE merchants (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mch_no TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  can_settle INTEGER NOT NULL DEFAULT 1,
  settlement_rate REAL DEFAULT 100,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE transactions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_no TEXT NOT NULL UNIQUE,
  mch_order_no TEXT,
  mch_no TEXT NOT NULL DEFAULT 'U1760418889',
  amount INTEGER NOT NULL,
  currency TEXT NOT NULL DEFAULT 'HKD',
  pay_type TEXT,
  subject TEXT,
  body TEXT,
  status INTEGER NOT NULL DEFAULT 0,
  payer_info TEXT,
  notify_url TEXT,
  return_url TEXT,
  raw_response TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  paid_at INTEGER,
  customer_ip TEXT
);

-- INDEXS

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX idx_merchants_mch_no ON merchants(mch_no);

CREATE INDEX idx_transactions_created_at ON transactions(created_at);

CREATE INDEX idx_transactions_mch_no ON transactions(mch_no);

CREATE INDEX idx_transactions_mch_status ON transactions(mch_no, status);

CREATE INDEX idx_transactions_order_no ON transactions(order_no);

CREATE INDEX idx_transactions_status ON transactions(status);
