// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, real } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const transactions = sqliteTable("transactions", {
	id: integer().primaryKey({ autoIncrement: true }),
	orderNo: text("order_no").notNull(),
	mchOrderNo: text("mch_order_no"),
	mchNo: text("mch_no").default("U1760418889").notNull(),
	amount: integer().notNull(),
	currency: text().default("HKD").notNull(),
	payType: text("pay_type"),
	subject: text(),
	body: text(),
	status: integer().default(0).notNull(),
	payerInfo: text("payer_info"),
	notifyUrl: text("notify_url"),
	returnUrl: text("return_url"),
	rawResponse: text("raw_response"),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`).notNull(),
	paidAt: integer("paid_at"),
	customerIp: text("customer_ip"),
},
(table) => [
	index("idx_transactions_mch_status").on(table.mchNo, table.status),
	index("idx_transactions_created_at").on(table.createdAt),
	index("idx_transactions_status").on(table.status),
	index("idx_transactions_mch_no").on(table.mchNo),
	index("idx_transactions_order_no").on(table.orderNo),
]);

export const merchants = sqliteTable("merchants", {
	id: integer().primaryKey({ autoIncrement: true }),
	mchNo: text("mch_no").notNull(),
	name: text().notNull(),
	isActive: integer("is_active").default(1).notNull(),
	canSettle: integer("can_settle").default(1).notNull(),
	settlementRate: real("settlement_rate").default(100),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`).notNull(),
},
(table) => [
	index("idx_merchants_mch_no").on(table.mchNo),
]);

